### ISSUE TITLE
updates so often / difficulty adjustment every 2-5mins ?

### ISSUE THREAD

**Issue by hannescrypto** [jacklevin74/xenminer#7]
dear jack, i am a XENMINER from few days back and i can say its quite fun and so on, but now i have to say the updates are getting more and more and how this right now works its quite a job to keep my server up to date, and sadly since the last updates today it looks more or less that we are mining only for getting new diffculty some seconds later, and i also found a superblock but this is not counted on the official site/leaderboard but only on the https://xen.pub/xenminer/leaderboard. And what would you reccomment for updating the miner.py instant or waiting, because on some days there are updates inert 4-5min again, which is quite more work to update and do it again 20min later :-(

**Comment by hannescrypto** [comment]
![image](https://github.com/jacklevin74/xenminer/assets/127392108/1e71a3a0-cc23-47cc-9155-6702bd093dc1)

**Comment by hannescrypto** [comment]
so is more or less wasted energie i guess when the miner adjust every few minutes :-(

**Comment by hannescrypto** [comment]
and what i found out with all these versions that the last version of the miner.py brings me much much less XUNI and XEN11 blocks then the releases before, maybe bad luck in finding or so, but i really dont get it whats wrong here right now

**Comment by dirrrtyjesus** [comment]
hannescrypto pls uninstall everything

**Comment by hannescrypto** [comment]
very helpful haha

**Comment by hannescrypto** [comment]
looks like its solved now

**Comment by dirrrtyjesus** [comment]
> looks like its solved now

thanks to you im sure!
